### ISSUE TITLE
Can it support websocket server

### ISSUE THREAD

**Issue by leeyisoft** [rancavil/tornado-rest#16]
I would like to add a hanlder file to the existing restful API to implement a websocket server

I want to share a port with other restful API

The code is as follows. How do I access the websocket server？

urls = [
    passport.IndexHandler,
    websocket.MsgServerHandler,
    # (r"/websocket",  websocket.MsgServerHandler),
]

class MsgServerHandler(tornado.websocket.WebSocketHandler, CommonHandler):
    current_user_id = ''
    waiters = {}
    cache = []
    cache_size = 200

**Comment by rancavil** [comment]
Great...!!!

**Comment by leeyisoft** [comment]
Could you please merge my last two submissions to master
https://github.com/leeyisoft/tornado-rest
