### ISSUE TITLE
POST decorator can't consume nested dict object

### ISSUE THREAD

**Issue by herikiri** [rancavil/tornado-rest#3]
Useful python library,  but how to pass nested json object to POST decorator?

I tried to post some json params from REST client like POSTMAN:
`{ 
   "name": "John Doe",
   "details: {
       "address": "21st Street" 
   }
}`

Here's my  Server side code:

```
class User(object):
    name = str
    details = dict

class UserHandler(RestHandler):
   @post(_path="/user", _types=[User])
   def user(self, params):
         return params
```

gives me internal server error:

> Internal Server Error : 'dict' object has no attribute '**dict**'

Can you give me some example to consume nested dict object to POST decorator?

**Comment by rancavil** [comment]
hi, thanks for your feedback.

The dict type is not defined into the API. Instead you must create the service like this:

```
 import tornado.ioloop
 from pyrestful.rest import RestHandler, post, RestService

 class Detail(object):
      address = str

 class User(object):
      name = str
      details = Detail

 class UserHandler(RestHandler): 
      @post(_path="/user", _types=[User])
     def user(self, params):
          print(params.name)
          print(params.details.address)

          return params

 if __name__ == '__main__':
      app = RestService([UserHandler])
      app.listen(8080)
      tornado.ioloop.IOLoop.instance().start()
```

I tested with postman and the result that give is:

```
 {
      "name": "John Doe",
      "details": {
           "address": "21st Street"
       }
 }
```

Check your JSON

```
 { "name": "John Doe", "details: { "address": "21st Street" } }
```

detail without a quotation mark.

Let's review to incorporate a type dict.

Again, Thanks for your feedback.

**Comment by herikiri** [comment]
Hi, thanks for your reply.
So Helpful, 
more understand the pattern from your library by now

Sorry for some typo on my comment.
Cheers

**Comment by rancavil** [comment]
Thanks for your feedback

**Comment by sxyload** [comment]
what about list? 
i use {"dates":[20180808,20180809]} , hower it also failed

**Comment by raghavlane** [comment]
Hi @sxyload ,
This is due to an issue in the dependency package pyconvert.
Please refer [pyconvert array issue](https://github.com/rancavil/python-convert/issues/2) for the issue details.

I have fixed this issue in my pull request [raghavlane-pyconvert](https://github.com/raghavlane/python-convert).

Please make the changes in the pyconvert library and let me know if it helps.
